version: '3'
services:
  dev: # 任意の名前（ディレクトリ名 + dev がコンテナ名となります）
    build:
      context: .
      dockerfile: Dockerfile
    image: apnea-ecg
    ports:
      - "8888:8888"
    volumes:
      - .:/workdir
